# site settings
title: PP
subtitle: null
email: parasptl678@gmail.com
description: A versatile software developer proficient in web </br>and application designing, development and AI/ML
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Paras Patil
street_address: Radha Krishna Complex, Sector-25,
city: Kamothe
state: Maharashtra
zip_code: 410209
country: India
phone: +919284792481

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 5

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/paras2001-hub
  GitLab:
  Google-Plus: 
  Instagram: https://www.instagram.com/paras.patil._/
  LinkedIn: https://www.linkedin.com/in/parasp2001/
  Twitter:
  Facebook:
  Slack:

collections:
  - works
# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
